import { Track } from "./types";

export const initialTracks: Track[] = [
  {
    id: 1,
    title: "Aura of Silicon",
    slug: "corporate-tech-innovation-background-music",
    targetKeyword: "corporate tech innovation background music",
    bpm: 122,
    musicalKey: "D Major",
    genre: "Tech Ambient",
    moods: ["Visionary", "Sophisticated", "Forward-Thinking", "Focused"],
    useCases: ["SaaS Product Reveal", "Keynote Presentation", "Fintech Commercial", "Architecture Profile"],
    description: "Built around pulsating Prophet-6 analog synth arpeggios, warm sub-bass, and crisp minimal percussion. Designed specifically for technical narrations and software walkthroughs where mid-frequency headroom is paramount for voice clarity. Subtle builds without distracting melodic hooks.",
    previewAudioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_drone.ogg",
    coverImageUrl: "/covers/track-1.jpg",
    durationSeconds: 165,
    standardPriceCents: 1000,
    agencyPriceCents: 2000,
    broadcastPriceCents: 4000,
    isPublished: true,
    publishedAt: "2026-09-01T10:00:00Z",
    updatedAt: "2026-09-01T10:00:00Z",
    altMixes: [
      { id: "1-full", name: "Full Mix", type: "full", durationSeconds: 165, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_drone.ogg" },
      { id: "1-under", name: "Underscore (No Lead)", type: "underscore", durationSeconds: 165, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_space_atmosphere.ogg" },
      { id: "1-ambient", name: "Drumless / Ambient", type: "drumless", durationSeconds: 165, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/humming_engine_room.ogg" },
      { id: "1-60s", name: "60s Commercial Cut", type: "60s", durationSeconds: 60, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_drone.ogg" },
      { id: "1-30s", name: "30s Broadcast Spot", type: "30s", durationSeconds: 30, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_drone.ogg" },
      { id: "1-15s", name: "15s Social Teaser", type: "15s", durationSeconds: 15, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_drone.ogg" }
    ],
    stems: [
      { name: "01_Drums_Percussion_24-48k.wav", category: "Drums", format: "WAV 24-bit / 48kHz" },
      { name: "02_Analog_SubBass_Moog.wav", category: "Bass", format: "WAV 24-bit / 48kHz" },
      { name: "03_Prophet6_Arp_Main.wav", category: "Synths & Guitars", format: "WAV 24-bit / 48kHz" },
      { name: "04_Atmospheric_Pads_Reverb.wav", category: "Synths & Guitars", format: "WAV 24-bit / 48kHz" },
      { name: "05_Downlifters_Impacts.wav", category: "FX & Risers", format: "WAV 24-bit / 48kHz" },
      { name: "06_Master_Full_Mix_24-48k.wav", category: "Master", format: "WAV 24-bit / 48kHz" }
    ],
    syncMeta: {
      composer: "Julian Hayes",
      publisher: "B2B Production Music Sync (BMI)",
      proAffiliation: "BMI (100% Direct Pre-Cleared)",
      isrc: "US-B2B-26-00101",
      energyLevel: "Medium",
      instrumentation: ["Sequential Prophet-6", "Moog Subsequent 37", "Custom Modular Racks", "Linear Drum Machine"],
      soundPalette: ["Airy", "Pulsing", "Analog Glass", "Clean Transients"],
      tempoDescriptor: "Steady Modern Driving (122 BPM)"
    }
  },
  {
    id: 2,
    title: "Apex Drive",
    slug: "energetic-commercial-advertisement-music",
    targetKeyword: "energetic commercial advertisement music",
    bpm: 128,
    musicalKey: "A Minor",
    genre: "Commercial Pop",
    moods: ["Dynamic", "Uplifting", "Confident", "High-Energy"],
    useCases: ["TV Commercial", "Sports Promo", "Product Launch Teaser", "Automotive Campaign"],
    description: "Infectious four-on-the-floor kick, delayed Stratocaster funk riffs, buoyant synth bass, and handclaps that drive relentless momentum. Arranged with natural edit points at :15, :30, and :60 for effortless commercial video adaptation.",
    previewAudioUrl: "https://actions.google.com/sounds/v1/science_fiction/space_engine_large.ogg",
    coverImageUrl: "/covers/track-2.jpg",
    durationSeconds: 172,
    standardPriceCents: 1000,
    agencyPriceCents: 2000,
    broadcastPriceCents: 4000,
    isPublished: true,
    publishedAt: "2026-09-02T10:00:00Z",
    updatedAt: "2026-09-02T10:00:00Z",
    altMixes: [
      { id: "2-full", name: "Full Mix", type: "full", durationSeconds: 172, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/space_engine_large.ogg" },
      { id: "2-under", name: "Underscore (No Guitar Hook)", type: "underscore", durationSeconds: 172, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/scifi_engine_hum.ogg" },
      { id: "2-drumless", name: "Percussionless Bed", type: "drumless", durationSeconds: 172, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/humming_engine_room.ogg" },
      { id: "2-60s", name: "60s Broadcast Cut", type: "60s", durationSeconds: 60, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/space_engine_large.ogg" },
      { id: "2-30s", name: "30s Commercial Cut", type: "30s", durationSeconds: 30, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/space_engine_large.ogg" },
      { id: "2-15s", name: "15s Logo Sting", type: "15s", durationSeconds: 15, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/space_engine_large.ogg" }
    ],
    stems: [
      { name: "01_Punchy_Kicks_Snares.wav", category: "Drums", format: "WAV 24-bit / 48kHz" },
      { name: "02_Sidechain_SynthBass.wav", category: "Bass", format: "WAV 24-bit / 48kHz" },
      { name: "03_Electric_Guitars_Funk.wav", category: "Synths & Guitars", format: "WAV 24-bit / 48kHz" },
      { name: "04_Synth_Chords_Plucks.wav", category: "Synths & Guitars", format: "WAV 24-bit / 48kHz" },
      { name: "05_Risers_Impacts_Claps.wav", category: "FX & Risers", format: "WAV 24-bit / 48kHz" },
      { name: "06_Master_WAV.wav", category: "Master", format: "WAV 24-bit / 48kHz" }
    ],
    syncMeta: {
      composer: "Marcus Sterling",
      publisher: "B2B Production Music Sync (ASCAP)",
      proAffiliation: "ASCAP (100% Direct Pre-Cleared)",
      isrc: "US-B2B-26-00102",
      energyLevel: "High",
      instrumentation: ["Fender American Stratocaster", "Vintage Oberheim OB-6", "Live Percussion", "Sidechained Sub"],
      soundPalette: ["Bright", "Crisp", "Punchy", "Optimistic"],
      tempoDescriptor: "Energetic Dance Tempo (128 BPM)"
    }
  },
  {
    id: 3,
    title: "Heritage Road",
    slug: "acoustic-folk-lifestyle-brand-music",
    targetKeyword: "acoustic folk lifestyle brand music",
    bpm: 104,
    musicalKey: "G Major",
    genre: "Acoustic Folk",
    moods: ["Organic", "Warm", "Heartfelt", "Inspiring"],
    useCases: ["Brand Origin Story", "Sustainable Products", "Tourism & Travel Campaign", "Non-Profit Film"],
    description: "Intimate fingerpicked Martin acoustic guitars, rustic wood block stomps, gentle glockenspiel top notes, and a bowed upright cello. Delivers authentic human emotion and organic warmth without sounding sentimental or manufactured.",
    previewAudioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_space_atmosphere.ogg",
    coverImageUrl: "/covers/track-3.jpg",
    durationSeconds: 154,
    standardPriceCents: 1000,
    agencyPriceCents: 2000,
    broadcastPriceCents: 4000,
    isPublished: true,
    publishedAt: "2026-09-03T10:00:00Z",
    updatedAt: "2026-09-03T10:00:00Z",
    altMixes: [
      { id: "3-full", name: "Full Acoustic Ensemble", type: "full", durationSeconds: 154, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_space_atmosphere.ogg" },
      { id: "3-guitar", name: "Solo Acoustic Guitar Only", type: "underscore", durationSeconds: 154, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/humming_engine_room.ogg" },
      { id: "3-nostomp", name: "Drumless / No Stomps", type: "drumless", durationSeconds: 154, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_space_atmosphere.ogg" },
      { id: "3-60s", name: "60s Narrative Edit", type: "60s", durationSeconds: 60, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_space_atmosphere.ogg" },
      { id: "3-30s", name: "30s Commercial Spot", type: "30s", durationSeconds: 30, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_space_atmosphere.ogg" }
    ],
    stems: [
      { name: "01_Acoustic_Guitar_Martin_D28.wav", category: "Acoustic Elements", format: "WAV 24-bit / 48kHz" },
      { name: "02_Stomps_Claps_Tambourine.wav", category: "Drums", format: "WAV 24-bit / 48kHz" },
      { name: "03_Upright_Bass_Mic.wav", category: "Bass", format: "WAV 24-bit / 48kHz" },
      { name: "04_Glockenspiel_Mandolin.wav", category: "Acoustic Elements", format: "WAV 24-bit / 48kHz" },
      { name: "05_Cello_Swells.wav", category: "Acoustic Elements", format: "WAV 24-bit / 48kHz" },
      { name: "06_Master_Mix.wav", category: "Master", format: "WAV 24-bit / 48kHz" }
    ],
    syncMeta: {
      composer: "Silas Vance",
      publisher: "B2B Production Music Sync (BMI)",
      proAffiliation: "BMI (100% Direct Pre-Cleared)",
      isrc: "US-B2B-26-00103",
      energyLevel: "Medium",
      instrumentation: ["Martin D-28 Acoustic", "Upright Bass", "Eastman Mandolin", "Real Barn Stomps"],
      soundPalette: ["Woody", "Earthy", "Analog Warmth", "Natural Room Reverb"],
      tempoDescriptor: "Relaxed Steady Strumming (104 BPM)"
    }
  },
  {
    id: 4,
    title: "Ascent of Kings",
    slug: "cinematic-documentary-ambient-music",
    targetKeyword: "cinematic documentary ambient music",
    bpm: 88,
    musicalKey: "D Minor",
    genre: "Cinematic Hybrid",
    moods: ["Heroic", "Monumental", "Dramatic", "Reflective"],
    useCases: ["Theatrical Trailer", "Documentary Climax", "Corporate Milestone Video", "Esports Championship"],
    description: "Majestic brass swells, relentless ostinato cellos, thunderous cinematic sub-hits, and soaring French horns. Rises through three distinct dramatic acts with natural breathing pauses for video transitions and voiceover sync points.",
    previewAudioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_drone.ogg",
    coverImageUrl: "/covers/track-4.jpg",
    durationSeconds: 198,
    standardPriceCents: 1000,
    agencyPriceCents: 2000,
    broadcastPriceCents: 4000,
    isPublished: true,
    publishedAt: "2026-09-04T10:00:00Z",
    updatedAt: "2026-09-04T10:00:00Z",
    altMixes: [
      { id: "4-full", name: "Full Hybrid Trailer Mix", type: "full", durationSeconds: 198, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_drone.ogg" },
      { id: "4-strings", name: "Orchestral Only (No Modern Synths)", type: "underscore", durationSeconds: 198, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_space_atmosphere.ogg" },
      { id: "4-ambient", name: "Ambient Piano & Drone Bed", type: "drumless", durationSeconds: 198, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/humming_engine_room.ogg" },
      { id: "4-60s", name: "60s Theatrical Trailer Cut", type: "60s", durationSeconds: 60, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_drone.ogg" },
      { id: "4-30s", name: "30s Teaser Cut", type: "30s", durationSeconds: 30, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_drone.ogg" }
    ],
    stems: [
      { name: "01_Taiko_Epic_Percussion.wav", category: "Drums", format: "WAV 24-bit / 48kHz" },
      { name: "02_Orchestral_Strings_Ensemble.wav", category: "Acoustic Elements", format: "WAV 24-bit / 48kHz" },
      { name: "03_Brass_Horns_Trombones.wav", category: "Acoustic Elements", format: "WAV 24-bit / 48kHz" },
      { name: "04_Trailer_Braams_SubHits.wav", category: "FX & Risers", format: "WAV 24-bit / 48kHz" },
      { name: "05_Solo_Cello_Melody.wav", category: "Acoustic Elements", format: "WAV 24-bit / 48kHz" },
      { name: "06_Master_Score.wav", category: "Master", format: "WAV 24-bit / 48kHz" }
    ],
    syncMeta: {
      composer: "Elena Rostova",
      publisher: "B2B Production Music Sync (BMI)",
      proAffiliation: "BMI / PRS (100% Direct Pre-Cleared)",
      isrc: "US-B2B-26-00104",
      energyLevel: "Explosive",
      instrumentation: ["Live 40-Piece String Ensemble", "French Horn Section", "Custom Japanese Taiko", "Analog Sub Braams"],
      soundPalette: ["Gargantuan", "Cinematic Reverb", "Dark Tension", "Heroic"],
      tempoDescriptor: "Deliberate Epic March (88 BPM)"
    }
  },
  {
    id: 5,
    title: "Silicon Sunset",
    slug: "lo-fi-tech-podcast-intro-music",
    targetKeyword: "lo-fi tech podcast intro music",
    bpm: 84,
    musicalKey: "F Major",
    genre: "Tech Lo-Fi",
    moods: ["Chill", "Reflective", "Analytical", "Warm"],
    useCases: ["Tech Podcast Intro", "Developer Live Stream", "Product Tutorial", "YouTube Educational Series"],
    description: "Saturated Rhodes electric piano running through 1/4-inch tape delay, vintage vinyl grit, relaxed sidechained hip-hop pocket drums, and a round upright bass. Calibrated precisely to avoid colliding with male and female vocal speech frequencies (300Hz - 3.5kHz).",
    previewAudioUrl: "https://actions.google.com/sounds/v1/science_fiction/space_engine_large.ogg",
    coverImageUrl: "/covers/track-1.jpg",
    durationSeconds: 138,
    standardPriceCents: 1000,
    agencyPriceCents: 2000,
    broadcastPriceCents: 4000,
    isPublished: true,
    publishedAt: "2026-09-05T10:00:00Z",
    updatedAt: "2026-09-05T10:00:00Z",
    altMixes: [
      { id: "5-full", name: "Full Beat & Keys Mix", type: "full", durationSeconds: 138, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/space_engine_large.ogg" },
      { id: "5-keys", name: "Solo Rhodes & Vinyl (No Beat)", type: "underscore", durationSeconds: 138, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/humming_engine_room.ogg" },
      { id: "5-loop", name: "Seamless 15s Podcast Bed Loop", type: "15s", durationSeconds: 15, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/space_engine_large.ogg" },
      { id: "5-30s", name: "30s Quick Intro Cut", type: "30s", durationSeconds: 30, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/space_engine_large.ogg" }
    ],
    stems: [
      { name: "01_SP404_TapeDrums.wav", category: "Drums", format: "WAV 24-bit / 48kHz" },
      { name: "02_Vintage_Rhodes73.wav", category: "Synths & Guitars", format: "WAV 24-bit / 48kHz" },
      { name: "03_Warm_SubBass.wav", category: "Bass", format: "WAV 24-bit / 48kHz" },
      { name: "04_VinylCrack_TapeFlutter.wav", category: "FX & Risers", format: "WAV 24-bit / 48kHz" },
      { name: "05_Master_Stereo.wav", category: "Master", format: "WAV 24-bit / 48kHz" }
    ],
    syncMeta: {
      composer: "David Karr",
      publisher: "B2B Production Music Sync (ASCAP)",
      proAffiliation: "ASCAP (100% Direct Pre-Cleared)",
      isrc: "US-B2B-26-00105",
      energyLevel: "Subtle",
      instrumentation: ["Fender Rhodes Mark I", "Roland SP-404 MKII", "Akai MPC Live", "Analog Tape Machine"],
      soundPalette: ["Dusty", "Vintage Tape", "Mellow", "Headroom-Optimized"],
      tempoDescriptor: "Downtempo Groove (84 BPM)"
    }
  },
  {
    id: 6,
    title: "Glass & Steel",
    slug: "modern-minimalist-architecture-piano",
    targetKeyword: "modern minimalist architecture piano",
    bpm: 96,
    musicalKey: "C Major",
    genre: "Minimalist Modern",
    moods: ["Elegant", "Prestigious", "Calculated", "Timeless"],
    useCases: ["Luxury Real Estate", "Executive Profile", "Design Documentary", "Corporate Annual Report"],
    description: "Intimate felt Yamaha upright piano with mechanical pedal clicks, sparse cello arpeggios, and subtle glass-like modular bells. Captures precision, craftsmanship, and quiet authority. Unobtrusive pacing built for architectural fly-throughs and luxury visual storytelling.",
    previewAudioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_drone.ogg",
    coverImageUrl: "/covers/track-2.jpg",
    durationSeconds: 148,
    standardPriceCents: 1000,
    agencyPriceCents: 2000,
    broadcastPriceCents: 4000,
    isPublished: true,
    publishedAt: "2026-09-06T10:00:00Z",
    updatedAt: "2026-09-06T10:00:00Z",
    altMixes: [
      { id: "6-full", name: "Full Piano & Strings Mix", type: "full", durationSeconds: 148, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_drone.ogg" },
      { id: "6-solo", name: "Solo Felt Piano Only", type: "underscore", durationSeconds: 148, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_space_atmosphere.ogg" },
      { id: "6-strings", name: "Sparse Cello Bed", type: "drumless", durationSeconds: 148, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/humming_engine_room.ogg" },
      { id: "6-60s", name: "60s Commercial Cut", type: "60s", durationSeconds: 60, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_drone.ogg" },
      { id: "6-30s", name: "30s Broadcast Cut", type: "30s", durationSeconds: 30, audioUrl: "https://actions.google.com/sounds/v1/science_fiction/deep_drone.ogg" }
    ],
    stems: [
      { name: "01_Felt_Upright_Piano_CloseMic.wav", category: "Acoustic Elements", format: "WAV 24-bit / 48kHz" },
      { name: "02_Cello_Ensemble_Staccato.wav", category: "Acoustic Elements", format: "WAV 24-bit / 48kHz" },
      { name: "03_Glass_Bells_Sine.wav", category: "Synths & Guitars", format: "WAV 24-bit / 48kHz" },
      { name: "04_Room_Tone_PedalNoise.wav", category: "FX & Risers", format: "WAV 24-bit / 48kHz" },
      { name: "05_Master_WAV.wav", category: "Master", format: "WAV 24-bit / 48kHz" }
    ],
    syncMeta: {
      composer: "Clara Lindqvist",
      publisher: "B2B Production Music Sync (BMI)",
      proAffiliation: "STIM / BMI (100% Direct Pre-Cleared)",
      isrc: "US-B2B-26-00106",
      energyLevel: "Subtle",
      instrumentation: ["Yamaha U1 Felt Upright", "Solo Violoncello", "Eurorack Modular Sine Waves", "Coles 4038 Ribbon Mics"],
      soundPalette: ["Intimate", "Glassy", "Pristine", "Acoustic Felt"],
      tempoDescriptor: "Delicate Neo-Classical (96 BPM)"
    }
  }
];
